export const sampleSymptoms = [
    "Suddenly she felt a sharp pain in her neck, shoulder, waist, arm, leg, stomach.",
    "Take an aspirin to relieve the pain.",
    "I can’t sleep because my head aches too bad.",
    "I have a terrible headache, backache, stomach-ache.",
    "My elder sister is seriously ill in St John’s hospital.",
    "The children started to feel ill an hour after the meal.",
    "I feel very sick, I don’t think I can work today.",
    "Be careful with the cake, too much of it can make you sick.",
    "I have a sore throat, I mustn’t take that cold drink.",
    "She says her stomach is still sore after the operation.",
    "His feet were sore after the bicycle trip.",
    "Our secretary missed a lot of work through illness last month.",
    "Flu can be a serious illness if you aren’t careful enough.",
    "Peter’s uncle suffers from a rare blood disease.",
    "A fatty diet increases the risk of heart disease.",
    "The government is planning further health measures to prevent the spread of disease.",
    "As I see it will take a long time for your wounds to heal.",
    "This ointment will help to heal your scratches.",
    "The tea you made really healed me.",
    "He was seriously ill for a long time, but the doctor cured him at last.",
    "Scarlet fever is a serious illness, but it can be cured fairly fast.",
    "There is no known cure for this illness but the it can be treated.",
    "I’m afraid you must be taken to hospital for the cure.",
    "I was treated for flu, but later I was diagnosed with pneumonia.",
    "This illness is usually treated with antibiotics and a strict diet.",
    "Doctors apply various treatments for this illness.",
    "My sister goes to a wellness centre to receive beauty treatments.",
    "The blood test is used to diagnose all kinds of diseases.",
    "She was diagnosed as a diabetic in her early childhood.",
    "The doctors didn’t share every detail of the diagnosis with the patient’s family.",
    "We had to wait a lot for the exact diagnosis after the examination.",
    "They were lucky to escape the fight without serious injuries.",
    "There were only minor injuries in the crash.",
    "He injured his finger when he was cutting the meat.",
    "Nobody was killed in the accident, but two people were seriously injured.",
    "He died from the wounds that he had received in the crash.",
    "He was taken to hospital although his wounds didn’t seem too serious.",
    "He had such a deep cut on his arm that he was taken to hospital.",
    "The victim had several cuts on his chest, still he survived.",
    "He was covered in bruises at the end of the football match.",
    "The man came to the surgery with a huge bruise over his eye.",
    "The cat continuously scratched itself behind the ear.",
    "She had a long scratch on her arm when she came out of the rose garden.",
    "Wash your hands carefully to decrease the risk of infection.",
    "She almost died from blood infection.",
    "My knee was twice the size of the other one due to the inflammation.",
    "You had better not eat fatty food so soon after your stomach inflammation.",
    "You don’t necessarily need a doctor with symptoms like a headache or sore throat.",
    "Depression can cause physical symptoms, too.",
    "have a temperature – when your temperature is higher than normal due to illness",
    "I feel so weak, I think I have a temperature.",
    "She had such a high temperature that she was immediately taken to hospital.",
    "Did you take aspirin to reduce the fever?",
    "Our daughter has been diagnosed with scarlet fever.",
    "I think I caught a cold on the ice rink yesterday.",
    "She can’t come to school, she’s in bed with a cold.",
    "Please don’t visit us this week, the whole family has the flu.",
    "If you’re not careful enough and you don’t take antibiotics, you may even die from the flu.",
    "There must have been something wrong with the food as both children vomited shortly after the meal.",
    "I’m afraid I’m pregnant; I vomit after getting up every morning.",
    "You look so pale. Haven’t you taken your medicine this morning?",
    "The doctor prescribed three kinds of medicine for me.",
    "My mum’s throat infection went away after she started the antibiotics.",
    "Hot tea won’t be enough to cure your flu, I think you also need antibiotics.",
    "I had such a horrible headache last night that I took two pain killers.",
    "She says she doesn’t think it’s a good idea to take pain killers too often.",
    "Drink some coffee if you feel your blood pressure is too low.",
    "High blood pressure increases the risk of having a heart attack.",
    "The doctor started the examination with taking my pulse and blood pressure.",
    "He has such a weak pulse that it’s hard to feel.",
    "They took x-rays of my knee to make sure it wasn’t broken.",
    "The doctor says that the x-ray has proved his suspicion of cancer, but I don’t believe him.",
    "The doctor examined the patient very carefully but he didn’t find any disorder.",
    "There were so many patients in the doctor’s surgery that I didn’t wait and I went home.",
    "I wanted to see a doctor but the surgery was closed.",
    "I hope they can cure me with medicine and I don’t need undergo surgery.",
    "The operation was successful but the patient died.",
    "The doctor says I can hardly escape an operation.",
    "He soon recovered after he was operated on for appendicitis.",
    "The doctor ordered to take my brother to hospital and they will operate on him tomorrow.",
    "The patient died on the way to the operating theatre.",
    "She felt nervous as she looked round the operating theatre",
    "The doctor suggested to go to the chemist’s for the medicine straight from the surgery.",
    "This syrup is also sold in the supermarket, so you don’t need to go to the chemist’s.",
    "Unfortunately, the doctor forgot to sign the prescription and so the chemist refused to give me the medicine.",
    "Keep this prescription even though you don’t need the medicine now; you may need it later.",
    "I think you should see a doctor.",
    "You look very pale. Shall I call the ambulance?",
    "I’m ill. I don’t feel well. I need a doctor. I must see a doctor.",
    "Doctor Bulb’s surgery hours are from 9 to 12 every morning.",
    "Where do I find the GP’s office? (general practitioner – a doctor who is trained in general medicine working in the local community)",
    "What are the consulting hours of the ENT (ear, nose and throat) specialist?",
    "Do I have to make an appointment?",
    "What’s the matter? Where’s the pain? What do you complain of?",
    "Have you taken your temperature?",
    "For how long have you been feeling ill?",
    "Take your clothes off. I’ll examine you. Let me take your pulse, please.",
    "I’ll measure your blood pressure.",
    "Your blood pressure is rather high. Your blood pressure is too low.",
    "Let me sound your back. Take a deep breath. I’ll check your lungs.",
    "Can I have a look? Where does it hurt?",
    "Does it hurt here? Breath out slowly.",
    "Show me your tongue. Poke out your tongue.",
    "Have you got any other symptoms?",
    "What infectious diseases have you had?",
    "What have you eaten/drunk?",
    "Have you been injured?",
    "Don’t worry. There’s no serious problem.",
    "I don’t think it’s too serious.",
    "You’ve got to be vaccinated against tetanus.",
    "You must stay in bed and take this medicine three times a day, after meals.",
    "I’ll dress the wound and put a plaster on your arm.",
    "You must follow a diet, you need to rest and you shouldn’t worry.",
    "Your test results have come in. The blood test came back negative.",
    "The biopsy shows a tumour.",
    "You should consult a specialist.",
    "We’ll know more in a few days.",
    "It would be better if you went to hospital.",
    "I think you’ll have to stay in hospital for a week.",
    "Hopefully, there won’t be any complications.",
    "I don’t think you need chemotherapy.",
    "I’ll give you a prescription. Take this medicine three times a day / after meals / an hour before lunch.",
    "You’ll soon be well again.",
    "Come back next week if you don’t feel better.",
    "I’ve got a high temperature.",
    "I feel really rough. I’m shattered/exhausted.",
    "Could you check my blood pressure? I’ve got high blood pressure.",
    "There’s a sharp pain here. I’ve got a pain in my limbs.",
    "I feel dizzy. I’ve got a kidney problem. I’ve lost weight.",
    "I always feel bad after meals. I’ve got a stomach ache.",
    "I’ve got a splitting headache. I often have nosebleeds.",
    "I have diarrhoea. I’ve lost my appetite.",
    "I’ve got circulation problems. I sweat all night.",
    "My ears are buzzing. I’ve got an upset stomach.",
    "I’ve sprained my wrist/ankle. My hand/foot is badly swollen.",
    "I think I’ve pulled a muscle in my leg/arm.",
    "I’ve had scarlet fever, mumps, the measles.",
    "Is it something serious? Is this a common problem at my age?",
    "When will the tests results come in? Are you going to run more tests?",
    "Do I have to be operated on? Will I need surgery?",
    "How long do I have to stay in hospital?",
    "I hope there won’t be any complications.",
    "Could you prescribe some medicine for me?",
    "How often should I take this medicine?",
    "Shall I come back next week if I don’t get better?",
    "I’ve got a pain in my back teeth and my gum is bleeding.",
    "I’ve lost a filling. My denture’s broken.",
    "Does the tooth have to be extracted or can you replace the filling?",
    "Would you make up this prescription for me?",
    "Shake well before use. Not to be taken orally.",
    "Can I get a packet of vitamin tablets?",
];
